apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: endpoints-cronjob
spec:
  schedule: "* * * * *" # run every minute
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: JOB_NAME
              image: eu.gcr.io/oceanic-throne-227920/highlights-bot:${CIRCLE_SHA1}
              command: ["/bin/bash", "-c", "gunicorn highlights.wsgi -b 0.0.0.0:8000"]
              env:
                - name: GCLOUD_PROJECT
                  value: PROJECT_NAME
                # endpoint to hit by cron job
                - name: FOREIGN_SERVICE
                  value: http://endpoints.default.svc.cluster.local/endpoint
                - name: NODE_ENV
                  value: production
          restartPolicy: Never