apiVersion: v1
kind: Service
metadata:
  name: highlights-bot-nodeport
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: highlights-bot-web

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: highlights-bot-ingress
spec:
  backend:
    serviceName: highlights-bot-nodeport
    servicePort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: highlights-bot-web-deployment
  labels:
    app: highlights-bot-web
spec:
  selector:
    matchLabels:
      app: highlights-bot-web
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: highlights-bot-web
    spec:
      containers:
      - name: web
        image: eu.gcr.io/oceanic-throne-227920/highlights-bot:${CIRCLE_SHA1}
        command: ["/bin/bash", "-c", "gunicorn highlights.wsgi -b 0.0.0.0:8000"]
        ports:
          - containerPort: 8000
        resources:
          requests:
            cpu: 0.2
        envFrom:
          - configMapRef:
              name: django-env-config

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: highlights-bot-horizontal-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: highlights-bot-web-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70