service: scheduled-tasks

provider:
  name: aws
  runtime: python3.6
  region: eu-west-2    # Deploy in London
  stage: prod
  timeout: 30

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - scheduler.py
    - scheduler_helpers/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  fetch:
    handler: scheduler.fetch_highlightsfootball_highlights

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: /
          method: get
#      - schedule: rate(10 minutes)

#    Define function environment variables here
#    environment:
#      variable2: value2


# plugins for python requirements
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux